apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-deployment
  labels:
    app: sentiment
spec:
  replicas: 2  # Adjust this based on your resource needs
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
      - name: sentiment
        image: gketan91/sentiment-webapp:latest
        ports:
        - containerPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentiment-ingress
spec:
  rules:
  - http:
      paths:
      - path: /  # Route all traffic to the root path
        pathType: Prefix
        backend:
          service:
            name: sentiment-deploymenadsdfdst
            port:
              number: 8000  # Match the Service port

  # Optional: Add additional path rules for specific routing
  # - http:
  #     paths:
  #     - path:   #       backend:
  #         service:
  #           name: my-api-service
  #           port:
  #             number: 8080
