apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-deployment
  labels:
    app: sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
      - name: sentiment
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-deployment
spec:
  selector:
    app: sentiment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
