apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-deployment
  labels:
    app: sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
      - name: sentiment
        image: gketan91/sentiment-webapp:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-deployment
spec:
  selector:
    app: sentiment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---