version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      # Other build steps...

      - run:
          name: Build Docker image
          command: |
            docker build -t myflaskapp .
