version: 2.1
jobs:
  build:
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Build Docker image
          command: |
            docker build -t ${CIRCLE_BUILD_NUM}:latest .

      - deploy:
          name: Deploy to Heroku
          command: |
			docker run -d -p 8000:8000 --name sent1 ${CIRCLE_BUILD_NUM}
            
