name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Docker@0
    displayName: Build an image
    inputs:
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: f9e1c5ba-25de-43ff-814a-0890886beefa
      dockerFile: Dockerfile
      includeLatestTag: true
  - task: Docker@0
    displayName: Push an image
    inputs:
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: f9e1c5ba-25de-43ff-814a-0890886beefa
      action: Push an image
      includeLatestTag: true
  - task: CopyPublishBuildArtifacts@1
    displayName: 'Copy Publish Artifact: Build'
    inputs:
      Contents: deploment.yaml
      ArtifactName: Build
      ArtifactType: Container
...
